local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5 #before 5.0
  publish_frequency: 2 #before 2.0
  static_map: true
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.025 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 3
  inflation_radius: 0.3
